fix: RaftClient.addOrUpdateGroupInLock may fail in some case.
 com.github.dtprj.dongting.net.NetException: java.util.concurrent.ExecutionException: com.github.dtprj.dongting.raft.RaftException: group id removed: 1
 	at dongting.client@0.8.7/com.github.dtprj.dongting.raft.RaftClient.waitFuture(RaftClient.java:366)
 	at dongting.client@0.8.7/com.github.dtprj.dongting.raft.RaftClient.sendRequest(RaftClient.java:352)
 	at dongting.client@0.8.7/com.github.dtprj.dongting.dtkv.KvClient.sendSync(KvClient.java:152)
 	at dongting.client@0.8.7/com.github.dtprj.dongting.dtkv.KvClient.put(KvClient.java:218)
 	at dongting.server@0.8.7/com.github.dtprj.dongting.dtkv.server.WatchManagerTest.put(WatchManagerTest.java:268)
 	at dongting.server@0.8.7/com.github.dtprj.dongting.dtkv.server.WatchManagerTest.testEx2(WatchManagerTest.java:353)
 Caused by: java.util.concurrent.ExecutionException: com.github.dtprj.dongting.raft.RaftException: group id removed: 1
 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
 	at dongting.client@0.8.7/com.github.dtprj.dongting.raft.RaftClient.waitFuture(RaftClient.java:357)
 	... 5 more
 Caused by: com.github.dtprj.dongting.raft.RaftException: group id removed: 1
 	at dongting.client@0.8.7/com.github.dtprj.dongting.raft.RaftClient.processLeaderQueryResult(RaftClient.java:687)
 	at dongting.client@0.8.7/com.github.dtprj.dongting.raft.RaftClient.lambda$findLeader$9(RaftClient.java:675)
 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
 	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
 	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
 	at dongting.client@0.8.7/com.github.dtprj.dongting.raft.RaftClient.findLeader(RaftClient.java:675)
 	at dongting.client@0.8.7/com.github.dtprj.dongting.raft.RaftClient.addOrUpdateGroupInLock(RaftClient.java:250)
 	at dongting.client@0.8.7/com.github.dtprj.dongting.raft.RaftClient.clientAddOrUpdateGroup(RaftClient.java:194)
 	at dongting.server@0.8.7/com.github.dtprj.dongting.dtkv.server.WatchManagerTest.init(WatchManagerTest.java:196)
 	at dongting.server@0.8.7/com.github.dtprj.dongting.dtkv.server.WatchManagerTest.testEx2(WatchManagerTest.java:342)